const reportBase = '../data/reports/';
const sources = {health:'aegis_health_status_latest.json',gate:'aegis_evidence_gate_latest.json',daily:'aegis_daily_dry_run_hardened_latest.json',history:'aegis_pipeline_history_latest.json',watchlist:'a_share_watchlist_latest.json',crcl:'crcl_risk_monitor_latest.json',vanke:'000002.sz_risk_monitor_latest.json',digest:'feishu_daily_digest_dry_run.json',rolling:'a_share_point_in_time_rolling_backtest_latest.json',rollingHistory:'a_share_rolling_backtest_history_latest.json',audit:'a_share_rolling_backtest_raw_price_audit_latest.json'};
const byId = id => document.getElementById(id);
const esc = value => String(value ?? '数据未提供').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtPct = value => typeof value === 'number' ? `${(value * 100).toFixed(2)}%` : '数据未提供';
const stateLabel = value => ({NORMAL:'正常',PASS:'正常',WARNING:'注意',FAIL:'失败',BLOCKED:'已阻止',UNKNOWN:'数据不足',MISSING:'数据不足',Exit:'退出复核',Action:'可执行',Ready:'等待确认',Watch:'观察',Review:'观察'}[value] || '数据不足');
const tone = value => ['NORMAL','PASS','Action'].includes(value) ? 'good' : ['FAIL','BLOCKED','Exit'].includes(value) ? 'risk' : 'warn';
const tag = value => `<span class="tag ${tone(value)}">${esc(stateLabel(value))}</span>`;

function deriveDailyDecision(viewModel) {
  const reasons = [];
  const gate = viewModel.gate?.overall_verdict;
  const health = viewModel.health?.health_status;
  const latestRun = viewModel.daily?.overall_verdict;
  if (gate !== 'PASS') reasons.push('证据检查异常');
  if (health === 'FAIL' || health === 'BLOCKED') reasons.push('系统状态异常');
  if (latestRun === 'FAIL') reasons.push('最近自动检查失败');
  if (viewModel.invalidSources.length) reasons.push('关键数据不可读取');
  const risks = viewModel.positions.filter(p => p.riskVeto || p.status === 'Exit');
  if (risks.some(p => p.riskVeto)) reasons.push('风险否决生效');
  const actions = viewModel.watchlist.filter(x => x.status === 'Action');
  const ready = viewModel.watchlist.filter(x => x.status === 'Ready');
  const watch = viewModel.watchlist.filter(x => ['Watch','Review'].includes(x.status));
  const counts = {risk_count:risks.length,action_count:actions.length,ready_count:ready.length,watch_count:watch.length};
  if (reasons.length) return {state:'BLOCKED',title:'系统阻止行动',summary:'关键证据或自动检查异常。',allowed:'检查系统与数据',forbidden:'任何投资动作',next_check:'修复异常后重新检查',blocking_reasons:reasons,...counts};
  if (risks.length) return {state:'Risk / Exit',title:'今天优先处理风险',summary:`当前有 ${risks.length} 项持仓风险需要复核。`,allowed:'复核退出条件、核对持仓数据',forbidden:'新增仓位',next_check:'每日 08:00 自动检查',blocking_reasons:[],...counts};
  if (actions.length) return {state:'Action',title:'今天存在可执行候选',summary:`当前有 ${actions.length} 个候选满足条件。`,allowed:'查看证据和失效条件',forbidden:'系统自动下单',next_check:'下一次自动检查',blocking_reasons:[],...counts};
  if (ready.length) return {state:'Ready',title:'今天等待确认',summary:`当前有 ${ready.length} 个候选等待确认。`,allowed:'复核候选条件',forbidden:'未经复核新增仓位',next_check:'下一次自动检查',blocking_reasons:[],...counts};
  if (watch.length) return {state:'Watch / Review',title:'今天无需操作',summary:'当前没有可执行候选，继续观察，等待条件变化。',allowed:'复核风险和市场状态',forbidden:'因无新证据而强行交易',next_check:'下一次自动检查',blocking_reasons:[],...counts};
  return {state:'No Data',title:'数据不足',summary:'数据不足，禁止行动。',allowed:'等待数据生成',forbidden:'任何投资动作',next_check:'数据生成后重新检查',blocking_reasons:[],...counts};
}

async function read(name, invalid) { try { const response = await fetch(reportBase + name,{cache:'no-store'}); if (!response.ok) throw new Error(String(response.status)); return await response.json(); } catch { invalid.push(name); return null; } }
function humanRisk(value) { const text=String(value||''); if (/max_drawdown/.test(text)) return '最大回撤超过风险阈值'; if (/volatility/.test(text)) return '波动率超过风险阈值'; if (/liquidity_not_ok/.test(text)) return '流动性不足'; if (/high_volatility/.test(text)) return '高波动风险触发'; if (/severe_drawdown/.test(text)) return '严重回撤风险触发'; return '风险条件需要复核'; }
function positionFromRisk(report, fallback) { if (!report) return {...fallback,missing:true,status:'UNKNOWN',riskVeto:false,risks:[]}; const meta=report.report_metadata||{},current=report.current_status||{},exit=report.exit_watch_eligibility||{}; return {symbol:meta.symbol||fallback.symbol,name:meta.stock_name||fallback.name,market:meta.market||fallback.market,status:current.recommendation||'UNKNOWN',riskVeto:report.risk_veto===true,risks:exit.blocking_conditions||[],updated:meta.generated_at||current.last_updated,nextCheck:report.next_check,source:meta.report_type||fallback.source,missing:false}; }
function holdingCard(p) { const onlyMonitor=p.symbol==='00700.HK'; const risk=p.risks[0] ? humanRisk(p.risks[0]) : '当前风险数据未提供'; const action=p.status==='Exit' ? '复核退出条件' : p.missing ? '等待监控数据更新' : '继续观察'; const position=onlyMonitor?'仅有监控状态，未确认实际持仓':'持仓数量：持仓数据未提供；成本价：数据未提供'; return `<article class="card holding-card"><h3>${esc(p.symbol)} · ${esc(p.name)}</h3><p>${tag(p.status)} ${esc(p.market)}</p><p>${esc(position)}</p><p><b>当前价：</b>数据未提供　<b>浮动收益：</b>数据未提供</p><p><b>风险提示：</b>${esc(risk)}</p><p><b>失效条件：</b>${esc(risk)}</p><p><b>下一步动作：</b>${esc(action)}</p><p class="muted">下次检查：每日 08:00 或风险条件变化时</p></article>`; }
function riskCard(p) { const first=p.risks[0] ? humanRisk(p.risks[0]) : '风险原因数据未提供'; return `<article class="card"><h3>${esc(p.symbol)} · ${esc(p.name)}</h3><p>${tag(p.status)}</p><p class="risk-line">${esc(first)}</p><p><b>建议动作：</b>复核退出条件</p><p class="muted">最近更新：${esc(p.updated)}</p><details><summary>查看原因</summary><ul class="detail-list">${p.risks.length?p.risks.map(x=>`<li>${esc(humanRisk(x))}</li>`).join(''):'<li>数据未提供</li>'}</ul><p class="muted">数据来源：${esc(p.source)}<br>原始更新时间：${esc(p.updated)}</p></details></article>`; }
function candidateCard(stock) { const note=stock.status==='Action'?'满足可执行状态，仍须人工复核。':stock.status==='Ready'?'等待条件确认。':'继续观察，等待条件变化。'; return `<article class="card watch-card"><h3>${esc(stock.symbol)} · ${esc(stock.name)}</h3><p>${tag(stock.status)}</p><p><b>支持证据：</b>数据未提供</p><p><b>反对证据：</b>数据未提供</p><p><b>风险阻塞：</b>数据未提供</p><p><b>失效条件：</b>数据未提供</p><p class="muted">${note}　下次检查：每日自动检查</p></article>`; }
function stage(daily,name,label) { const row=(daily?.stages||[]).find(x=>x.name===name); return `<li>${label}：${esc(stateLabel(row?.result))}</li>`; }
function reportLink(label,name) { return `<li><a href="${reportBase}${esc(name)}" target="_blank" rel="noopener">${esc(label)}</a></li>`; }

function render() { const invalid=[]; return Promise.all(Object.entries(sources).map(async([key,file])=>[key,await read(file,invalid)])).then(entries=>{
  const d=Object.fromEntries(entries);
  const positions=[positionFromRisk(d.crcl,{symbol:'CRCL',name:'数据未提供',market:'US',source:'CRCL 风险监控'}),positionFromRisk(d.vanke,{symbol:'000002.SZ',name:'数据未提供',market:'A',source:'万科A风险监控'}),{symbol:'00700.HK',name:'数据未提供',market:'HK',status:d.health?.hk_00700_status==='MISSING'?'MISSING':'UNKNOWN',riskVeto:false,risks:[],updated:d.health?.generated_at,nextCheck:null,source:'港股监控状态',missing:true}];
  const watchlist=d.watchlist?.stocks||[]; const vm={health:d.health,gate:d.gate,daily:d.daily,positions,watchlist,invalidSources:invalid}; const decision=deriveDailyDecision(vm);
  const system=d.health?.health_status || d.gate?.overall_verdict || 'UNKNOWN'; const daily=d.daily?.overall_verdict || 'UNKNOWN';
  byId('today-date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
  byId('system-status').textContent=stateLabel(system); byId('daily-status').textContent=stateLabel(daily); byId('data-time').textContent=`数据更新时间：${d.health?.generated_at || d.daily?.generated_at || '数据未提供'}`;
  const hero=byId('decision'); hero.className=`section hero ${decision.state==='Risk / Exit'?'risk-state':decision.state==='BLOCKED'?'blocked-state':decision.state==='Watch / Review'||decision.state==='Ready'?'warn-state':''}`;
  byId('decision-content').innerHTML=`${tag(decision.state)}<h2 class="decision-title">${esc(decision.title)}</h2><p class="decision-summary">${esc(decision.summary)}</p><div class="decision-actions"><div class="directive"><b>今天允许做什么</b>${esc(decision.allowed)}</div><div class="directive forbid"><b>今天禁止做什么</b>${esc(decision.forbidden)}</div></div><div class="metrics"><div class="metric"><span>风险数量</span><strong>${decision.risk_count}</strong></div><div class="metric"><span>可执行候选</span><strong>${decision.action_count}</strong></div><div class="metric"><span>下次检查</span><strong>${esc(decision.next_check)}</strong></div></div>${decision.blocking_reasons.length?`<p class="muted">${esc(decision.blocking_reasons.join('；'))}</p>`:''}`;
  const risks=positions.filter(p=>p.status==='Exit'||p.riskVeto).slice(0,3); byId('risk-content').innerHTML=risks.length?risks.map(riskCard).join(''):'<p class="empty">当前没有紧急风险。</p>';
  byId('holdings-content').innerHTML=positions.map(holdingCard).join('');
  byId('next-content').innerHTML=`<p class="daily-line"><b>${esc(decision.next_check)}</b> · 每日 08:00 自动检查</p><p class="muted">出现风险条件、数据异常或自动检查失败时，应提前复核。</p>`;
  const actions=watchlist.filter(x=>x.status==='Action'); byId('action-content').innerHTML=actions.length?actions.map(candidateCard).join(''):'<p class="empty">当前没有可执行候选。</p>';
  const watchOnly=watchlist.filter(x=>x.status!=='Action'); const focus=watchOnly.slice(0,5); byId('watchlist-content').innerHTML=watchOnly.length?`<p class="watch-summary">观察名单（${watchOnly.length}）　重点关注：${focus.length} 只</p><div class="watch-grid">${focus.map(candidateCard).join('')}</div>${watchOnly.length>focus.length?`<details><summary>查看全部观察名单</summary><div class="watch-grid details-content">${watchOnly.slice(focus.length).map(candidateCard).join('')}</div></details>`:''}`:'<p class="empty">候选列表尚未生成。</p>';
  const a=watchlist.length?'谨慎（仅有观察候选）':'数据不足'; const hk=d.health?.hk_00700_status==='MISSING'?'数据不足':'数据不足'; const us=positions[0].status==='Exit'?'注意（存在退出复核）':'数据不足'; byId('market-content').innerHTML=`<p class="market-line">A股：<b>${a}</b>　港股：<b>${hk}</b>　美股：<b>${us}</b></p><p class="muted">仅在真实状态为可执行且无风险阻断时允许行动。</p>`;
  const metrics=d.rolling?.portfolio_metrics||{},benchmark=d.rolling?.benchmark_metrics||{}; byId('backtest-content').innerHTML=`<p class="research-notice">历史策略不等于当前 Watchlist。<br>回测结果不是实盘收益。</p><div class="research-summary"><div class="metric"><span>期数</span><strong>${esc(d.rolling?.periods_count)}</strong></div><div class="metric"><span>总收益</span><strong>${fmtPct(metrics.total_return)}</strong></div><div class="metric"><span>最大回撤</span><strong>${fmtPct(metrics.max_drawdown)}</strong></div><div class="metric"><span>基准收益</span><strong>${fmtPct(benchmark.total_return)}</strong></div><div class="metric"><span>超额收益</span><strong>${fmtPct(d.rolling?.excess_return)}</strong></div><div class="metric"><span>原始价格审计</span><strong>${esc(stateLabel(d.audit?.overall_verdict))}</strong></div></div><details><summary>查看研究条件</summary><ul class="detail-list"><li>年化收益：${fmtPct(metrics.annualized_return)}</li><li>波动率：${fmtPct(metrics.volatility)}</li><li>夏普比率：${esc(metrics.sharpe)}</li><li>胜率：${fmtPct(metrics.win_rate)}</li><li>要求按历史时点取数：${d.rolling?.point_in_time_required?'是':'否'}</li><li>静态快照回测：${d.rolling?.static_snapshot_backtest?'是':'否'}</li><li>存在幸存者偏差提示：${d.rolling?.survivorship_bias_warning?'是':'否'}</li><li>历史策略与当前候选等价：${d.rolling?.strategy_equivalence_claimed?'是':'否'}</li></ul></details>`;
  byId('daily-content').innerHTML=d.daily?`<p class="daily-line">每日 08:00　最近运行：${esc(d.daily.generated_at)}　结果：${tag(d.daily.overall_verdict)}　下次检查：每日 08:00</p><details><summary>查看检查详情</summary><ul class="detail-list">${stage(d.daily,'morning_health','系统健康')}${stage(d.daily,'rolling_pipeline','滚动回测')}${stage(d.daily,'final_evidence_gate','证据检查')}<li>锁残留：${d.daily.lock_recovery?.stale_lock_found?'有':'无'}</li></ul></details>`:'<p class="empty">自动检查状态未知。</p>';
  byId('evidence-content').innerHTML=`<p>证据检查：${tag(d.gate?.overall_verdict)}　数据流水线历史：${d.history?.runs?.length ?? '数据未提供'} 条记录　原始价格审计：${tag(d.audit?.overall_verdict)}</p><ul class="detail-list">${reportLink('证据检查',sources.gate)}${reportLink('数据流水线历史',sources.history)}${reportLink('原始价格审计',sources.audit)}${reportLink('滚动回测历史',sources.rollingHistory)}${reportLink('信号快照','a_share_signal_snapshots_latest.json')}</ul><p class="muted">不可读取数据：${invalid.length?esc(invalid.length):'无'}</p>`;
 }); }
byId('refresh').addEventListener('click',render); render();
