#!/usr/bin/env python3
"""
validate_aegis_health_status.py

Validates the health status report generated by build_aegis_health_status.py.
Exits with code 0 on success, non-zero on failure.
"""

import json
import sys
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = REPO_ROOT / "data" / "reports"

HEALTH_JSON = REPORTS_DIR / "aegis_health_status_latest.json"
HEALTH_MD = REPORTS_DIR / "aegis_health_status_latest.md"


def main() -> int:
    strict_mode = "--strict" in sys.argv
    
    print("[validate_aegis_health_status] starting …")
    
    # Prepare validation results
    results = {
        "project": "Project Aegis",
        "type": "health_status_validation",
        "validated_at": "2026-07-10T11:39:00.000000+08:00",  # This would normally be dynamic
        "strict_mode": strict_mode,
        "checks": {},
        "failures": [],
        "overall_verdict": "PASS"
    }
    
    # Check if health JSON exists
    health_json_exists = HEALTH_JSON.exists()
    results["checks"]["health_json_exists"] = {"passed": health_json_exists}
    if not health_json_exists:
        results["failures"].append("health_json_exists: file does not exist")
    
    # Check if health MD exists
    health_md_exists = HEALTH_MD.exists()
    results["checks"]["health_md_exists"] = {"passed": health_md_exists}
    if not health_md_exists:
        results["failures"].append("health_md_exists: file does not exist")
    
    # Check if JSON is parseable
    health_data = None
    json_parseable = False
    if health_json_exists:
        try:
            health_data = json.loads(HEALTH_JSON.read_text(encoding="utf-8"))
            json_parseable = True
        except Exception as e:
            json_parseable = False
            results["failures"].append(f"health_json_parseable: {str(e)}")
    
    results["checks"]["health_json_parseable"] = {"passed": json_parseable}
    if not json_parseable:
        results["failures"].append("health_json_parseable: JSON parsing failed")
    
    # Check health status if JSON is parseable
    health_status_valid = False
    if json_parseable and health_data:
        status = health_data.get("health_status")
        if status in ["NORMAL", "WARNING", "CRITICAL"]:
            health_status_valid = True
        else:
            results["failures"].append(f"health_status_valid: invalid status '{status}'")
    
    results["checks"]["health_status_valid"] = {"passed": health_status_valid}
    if not health_status_valid:
        results["failures"].append("health_status_valid: status not in [NORMAL, WARNING, CRITICAL]")
    
    # Check if current status is NORMAL (when strict)
    current_should_be_normal = False
    if strict_mode and json_parseable and health_data:
        if health_data.get("health_status") == "NORMAL":
            current_should_be_normal = True
        else:
            results["failures"].append(f"current_should_be_normal: expected NORMAL, got {health_data.get('health_status')}")
    
    results["checks"]["current_should_be_normal"] = {"passed": current_should_be_normal}
    if strict_mode and not current_should_be_normal:
        results["failures"].append("current_should_be_normal: health status should be NORMAL")
    
    # Check safety flags
    sent_is_false = False
    if json_parseable and health_data:
        sent_is_false = health_data.get("sent") is False
        if not sent_is_false:
            results["failures"].append(f"sent_is_false: expected False, got {health_data.get('sent')}")
    
    results["checks"]["sent_is_false"] = {"passed": sent_is_false}
    if not sent_is_false:
        results["failures"].append("sent_is_false: sent should be False")
    
    webhook_not_called = False
    if json_parseable and health_data:
        webhook_not_called = health_data.get("webhook_called") is False
        if not webhook_not_called:
            results["failures"].append(f"webhook_not_called: expected False, got {health_data.get('webhook_called')}")
    
    results["checks"]["webhook_not_called"] = {"passed": webhook_not_called}
    if not webhook_not_called:
        results["failures"].append("webhook_not_called: webhook_called should be False")
    
    trading_not_called = False
    if json_parseable and health_data:
        trading_not_called = health_data.get("trading_called") is False
        if not trading_not_called:
            results["failures"].append(f"trading_not_called: expected False, got {health_data.get('trading_called')}")
    
    results["checks"]["trading_not_called"] = {"passed": trading_not_called}
    if not trading_not_called:
        results["failures"].append("trading_not_called: trading_called should be False")
    
    # Check A-share Top5 count
    a_share_top5_count_5 = False
    if json_parseable and health_data:
        top5_count = len(health_data.get("a_share_top5_symbols", []))
        a_share_top5_count_5 = top5_count == 5
        if not a_share_top5_count_5:
            results["failures"].append(f"a_share_top5_count_5: expected 5, got {top5_count}")
    
    results["checks"]["a_share_top5_count_5"] = {"passed": a_share_top5_count_5}
    if not a_share_top5_count_5:
        results["failures"].append("a_share_top5_count_5: A-share Top5 count should be 5")
    
    # Secret scan
    secret_pattern = r'(token|secret|api.*key|cookie|webhook.*url|password|credential)'
    no_secrets_found = True
    if health_json_exists:
        content = HEALTH_JSON.read_text(encoding="utf-8")
        if re.search(secret_pattern, content, re.IGNORECASE):
            no_secrets_found = False
            results["failures"].append("no_secrets_found: potential secret detected in health JSON")
    
    results["checks"]["no_secrets_found"] = {"passed": no_secrets_found}
    if not no_secrets_found:
        results["failures"].append("no_secrets_found: potential secret detected in health JSON")
    
    # Overall verdict
    results["overall_verdict"] = "PASS" if not results["failures"] else "FAIL"
    
    print("HEALTH_STATUS_VERDICT_JSON")
    print(json.dumps(results, ensure_ascii=False, indent=2))
    print("END_HEALTH_STATUS_VERDICT_JSON")
    
    return 0 if results["overall_verdict"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
